работа с состоянием, новый компонент, новые маршруты
htmlacademy-react/1465455-guess-melody-5 pull request #6
Opened 2020-10-07 17:11 UTC by begemotv

2020-10-12 16:51 UTC, DmitryMarkov requested changes
тесты не проходят на сервере, скорее всего из-за console.log, надо поправить

2020-10-12 16:51 UTC, DmitryMarkov commented on src/components/app/app.jsx
> +  console.log(`click`)
консологи запрещены

2020-10-12 16:51 UTC, DmitryMarkov commented on src/components/game-screen/game-screen.jsx
> +              }));
Дупликация кода со строками 33-36, надо вынести в метод класса

2020-10-12 16:51 UTC, DmitryMarkov commented on src/components/game-screen/game-screen.jsx
> +  questions: PropTypes.array.isRequired,
Всегда стоит использовать arrayOf с указанием типа элементов массива

2020-10-12 16:51 UTC, DmitryMarkov commented on src/components/question-genre-screen/question-genre-screen.jsx
> +                    }}
любые коллбеки лучше выносить в методы класса, особенно такие сложные

2020-10-14 16:29 UTC, begemotv commented on src/components/app/app.jsx
> +  console.log(`click`)
Исправил

2020-10-14 16:30 UTC, begemotv commented on src/components/game-screen/game-screen.jsx
> +  questions: PropTypes.array.isRequired,
Исправил

2020-10-16 20:54 UTC, DmitryMarkov commented on src/components/question-genre-screen/question-genre-screen.jsx
> +                    }}
Я покажу на созвоне, есть отличная техника с использованием замыканий. Напомни, плиз

2020-10-16 20:55 UTC, DmitryMarkov approved these changes
Замечания исправлены. Проптайп можно поправить в следующем PR

2020-10-16 20:55 UTC, DmitryMarkov commented on src/components/game-screen/game-screen.jsx
> +  questions: PropTypes.arrayOf(PropTypes.object).isRequired,
object использовать тоже нельзя, только shape!

2020-10-16 20:56 UTC, merged